[workspace]
members = [
    "crates/sloth",
    "crates/sloth_bytecode",
    "crates/sloth_vm",
]

[profile.dev.package."*"]
opt-level = 2

[profile.release]
strip = "debuginfo"
lto = "thin"
opt-level = 3

