[package]
name = "sloth"

license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
llvm-sys = "150"
inkwell = { version = "0.2.0", features = ["llvm15-0"] }
itertools = "0.10.5"
rand = "0.8.5"
thiserror = "1.0.40"
