[package]
name = "sloth_vm"

license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
sloth_bytecode = { path = "../sloth_bytecode" }

once_cell = "1.17.1"
rand = "0.8.5"
