name: Linting
on: [push, pull_request]

jobs:
  dependency-lint:
    name: Dependency linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rm rust-toolchain.toml
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --all-features
          command-arguments: --allow license-not-encountered
  code-lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rm rust-toolchain.toml
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2023-06-19
          components: clippy, rust-src
      - run: cargo clippy --all-features -- --deny warnings
  code-format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rm rust-toolchain.toml
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2023-06-19
          components: rustfmt, rust-src
      - run: cargo fmt -- --check
